#action.yml
name: CI Status

description: 'Action for checking the CI status and notifying it to the maintainer'

inputs:
  email_token:
    description: Email secret
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    EMAIL_TOKEN: ${{ inputs.email_token }}
